package run

import (
	"bytes"
	"embed"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
	"unicode/utf8"

	"golang.org/x/mod/modfile"
	"golang.org/x/tools/imports"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

var (
	//go:embed client.go.tpl
	tmplData           embed.FS
	tmpl               = template.Must(template.ParseFS(tmplData, "client.go.tpl"))
	flags              = flag.FlagSet{}
	grpccorePkg        = protogen.GoImportPath("github.com/La-Perla-App/backend-core-laperla/pkg/api")
	packageName        = flags.String("package", "", "Package name for the generated client")
	baseImportPath     = flags.String("baseimportpath", "", "Base import path for the generated client")
	catalogsDir        = flags.String("catalogsdir", "catalogs", "Catalogs services package directory")
	clientAddressIdent = flags.String("clientaddressident", "ClientAddress", "Client address function found on catalogs package")
)

const (
	commentWidth = 97 // leave room for "// "
)

type MethodTemplate struct {
	MethodName            string
	RequestType           string
	ResponseType          string
	OutputIdent           string
	PrefixWithServiceName bool
	Deprecated            bool
	HasGateway            bool
}

type TemplateData struct {
	ProtoImportPath       string
	Package               string
	ProtoPackage          string
	PackagePath           string
	BaseImportPath        string
	ServiceName           string
	GeneralParamsIdent    string
	NewRequestIdent       string
	Methods               []MethodTemplate
	ServerEndpointIdent   string
	ConnectNewClientIdent string
	GetIdent              func(string, string) string
	GetConnectIdent       func(string) string
}

func parseGoMod() (string, error) {
	data, err := os.ReadFile("go.mod")
	if err != nil {
		return "", err
	}

	modFile, err := modfile.Parse("go.mod", data, nil)
	if err != nil {
		return "", err
	}

	return modFile.Module.Mod.Path, nil
}

func genPkgName(key string) string {
	key = regexp.MustCompile(`^\d+`).ReplaceAllString(key, "")
	return strings.ToLower(regexp.MustCompile(`[^a-zA-Z0-9]+`).ReplaceAllString(key, ""))
}

func generateFile(plugin *protogen.Plugin, file *protogen.File, service *protogen.Service, packagePath string, methodsMap map[string]struct{}) error {
	var buf bytes.Buffer

	generatedFilenamePrefixToSlash := path.Join(
		path.Dir(filepath.ToSlash(file.GeneratedFilenamePrefix)),
		genPkgName(service.GoName),
	)
	generatedFilenamePrefix := path.Join(
		path.Dir(generatedFilenamePrefixToSlash),
		"client",
		path.Base(generatedFilenamePrefixToSlash),
	)
	filename := generatedFilenamePrefix + ".client.go"
	goImportPath := protogen.GoImportPath(path.Join(
		string(file.GoImportPath),
		string(file.GoPackageName),
	))
	g := plugin.NewGeneratedFile(filename, goImportPath)

	programName := filepath.Base(os.Args[0])
	// Remove .exe suffix on Windows so that generated code is stable, regardless
	// of whether it was generated on a Windows machine or not.
	if ext := filepath.Ext(programName); strings.ToLower(ext) == ".exe" {
		programName = strings.TrimSuffix(programName, ext)
	}
	g.P("// Code generated by ", programName, ". DO NOT EDIT.")
	g.P("//")
	if file.Proto.GetOptions().GetDeprecated() {
		wrapComments(g, file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()

	g.Import(file.GoImportPath)

	getIdent := func(pkg, prop string) string {
		return g.QualifiedGoIdent(protogen.GoImportPath(pkg).Ident(prop))
	}
	getConnectIdent := func(prop string) string {
		return getIdent(path.Join(string(file.GoImportPath), string(file.GoPackageName)+"connect"), prop)
	}

	protoPackage := string(file.GoPackageName)
	if file.Proto.Package != nil {
		protoPackage = *file.Proto.Package
	}

	data := TemplateData{
		ProtoImportPath:       string(file.GoImportPath),
		Package:               string(file.GoPackageName),
		ProtoPackage:          protoPackage,
		PackagePath:           packagePath,
		ServiceName:           string(service.GoName),
		GeneralParamsIdent:    g.QualifiedGoIdent(grpccorePkg.Ident("GeneralParams")),
		NewRequestIdent:       g.QualifiedGoIdent(grpccorePkg.Ident("NewRequest")),
		ServerEndpointIdent:   g.QualifiedGoIdent(protogen.GoImportPath(path.Join(packagePath, *catalogsDir)).Ident(*clientAddressIdent)),
		ConnectNewClientIdent: getConnectIdent(fmt.Sprintf("New%sClient", service.GoName)),
		GetConnectIdent:       getConnectIdent,
		GetIdent:              getIdent,
	}

	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue
		}
		methodName := string(method.GoName)
		hasGateway := !(strings.Contains(method.Comments.Leading.String(), "@internal") ||
			strings.Contains(method.Comments.Trailing.String(), "@internal"))
		_, prefixWithServiceName := methodsMap[methodName]
		opts, ok := method.Desc.Options().(*descriptorpb.MethodOptions)
		deprecated := ok && opts != nil && opts.Deprecated != nil && *opts.Deprecated
		data.Methods = append(data.Methods, MethodTemplate{
			MethodName:            methodName,
			RequestType:           g.QualifiedGoIdent(method.Input.GoIdent),
			ResponseType:          g.QualifiedGoIdent(method.Output.GoIdent),
			PrefixWithServiceName: prefixWithServiceName,
			Deprecated:            deprecated,
			HasGateway:            hasGateway,
		})
		methodsMap[methodName] = struct{}{}
	}

	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	g.P(buf.String())
	content, err := g.Content()
	if err != nil {
		return err
	}
	g.Skip()
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	formatted, err = imports.Process(filename, content, nil)
	if err != nil {
		return err
	}
	g = plugin.NewGeneratedFile(filename, goImportPath)

	_, err = g.Write(formatted)
	return err
}

func wrapComments(g *protogen.GeneratedFile, elems ...any) {
	text := &bytes.Buffer{}
	for _, el := range elems {
		switch el := el.(type) {
		case protogen.GoIdent:
			fmt.Fprint(text, g.QualifiedGoIdent(el))
		default:
			fmt.Fprint(text, el)
		}
	}
	words := strings.Fields(text.String())
	text.Reset()
	var pos int
	for _, word := range words {
		numRunes := utf8.RuneCountInString(word)
		if pos > 0 && pos+numRunes+1 > commentWidth {
			g.P("// ", text.String())
			text.Reset()
			pos = 0
		}
		if pos > 0 {
			text.WriteRune(' ')
			pos++
		}
		text.WriteString(word)
		pos += numRunes
	}
	if text.Len() > 0 {
		g.P("// ", text.String())
	}
}

func Run() {
	protogen.Options{ParamFunc: flags.Set}.Run(func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		var packagePath string
		var err error
		if *packageName != "" {
			packagePath = *packageName
		} else {
			packagePath, err = parseGoMod()
			if err != nil {
				log.Fatalf("Failed to parse go.mod: %v", err)
			}
		}
		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			methodsMap := map[string]struct{}{}
			for _, service := range file.Services {
				if err := generateFile(plugin, file, service, packagePath, methodsMap); err != nil {
					return err
				}
			}
		}
		return nil
	})
}
